export function getUpcomingEvents(): Promise<any[]> {
  return new Promise((resolve, reject) => {
    resolve([
      {
        id: 0,
        title: "Event 1",
        description: "Will be about getting people together",
        eventStart: "23/01/2019",
        eventEnd: "25/01/2019",
        belongsToHubs: [null],
        venueName: "Sirikwa Hotel",
        address: "Oloo Street",
        city: "Eldoret",
        state: "Uasin Gishu",
        zipCode: "string",
        country: "Kenya",
        createdAt: "string",
        fqUrl: "string",
        paidForDomain: true,
        domain: "string",
        customDomain: "string",
        event_type: "string",
        splashTheme: {},
        ticketTypes: [null],
        groupIds: [0]
      },
      {
        id: 1,
        title: "Event 1",
        description: "Will be about getting people together",
        eventStart: "23/01/2019",
        eventEnd: "25/01/2019",
        belongsToHubs: [null],
        venueName: "Sirikwa Hotel",
        address: "Oloo Street",
        city: "Eldoret",
        state: "Uasin Gishu",
        zipCode: "string",
        country: "Kenya",
        createdAt: "string",
        fqUrl: "string",
        paidForDomain: true,
        domain: "string",
        customDomain: "string",
        event_type: "string",
        splashTheme: {},
        ticketTypes: [null],
        groupIds: [0]
      },
      {
        id: 2,
        title: "Event 1",
        description: "Will be about getting people together",
        eventStart: "23/01/2019",
        eventEnd: "25/01/2019",
        belongsToHubs: [null],
        venueName: "Sirikwa Hotel",
        address: "Oloo Street",
        city: "Eldoret",
        state: "Uasin Gishu",
        zipCode: "string",
        country: "Kenya",
        createdAt: "string",
        fqUrl: "string",
        paidForDomain: true,
        domain: "string",
        customDomain: "string",
        event_type: "string",
        splashTheme: {},
        ticketTypes: [null],
        groupIds: [0]
      },
      {
        id: 3,
        title: "Event 1",
        description: "Will be about getting people together",
        eventStart: "23/01/2019",
        eventEnd: "25/01/2019",
        belongsToHubs: [null],
        venueName: "Sirikwa Hotel",
        address: "Oloo Street",
        city: "Eldoret",
        state: "Uasin Gishu",
        zipCode: "string",
        country: "Kenya",
        createdAt: "string",
        fqUrl: "string",
        paidForDomain: true,
        domain: "string",
        customDomain: "string",
        event_type: "string",
        splashTheme: {},
        ticketTypes: [null],
        groupIds: [0]
      },
      {
        id: 4,
        title: "Event 1",
        description: "Will be about getting people together",
        eventStart: "23/01/2019",
        eventEnd: "25/01/2019",
        belongsToHubs: [null],
        venueName: "Sirikwa Hotel",
        address: "Oloo Street",
        city: "Eldoret",
        state: "Uasin Gishu",
        zipCode: "string",
        country: "Kenya",
        createdAt: "string",
        fqUrl: "string",
        paidForDomain: true,
        domain: "string",
        customDomain: "string",
        event_type: "string",
        splashTheme: {},
        ticketTypes: [null],
        groupIds: [0]
      },
      {
        id: 5,
        title: "Event 1",
        description: "Will be about getting people together",
        eventStart: "23/01/2019",
        eventEnd: "25/01/2019",
        belongsToHubs: [null],
        venueName: "Sirikwa Hotel",
        address: "Oloo Street",
        city: "Eldoret",
        state: "Uasin Gishu",
        zipCode: "string",
        country: "Kenya",
        createdAt: "string",
        fqUrl: "string",
        paidForDomain: true,
        domain: "string",
        customDomain: "string",
        event_type: "string",
        splashTheme: {},
        ticketTypes: [null],
        groupIds: [0]
      }
    ]);
  });
}
